books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path('', views.index_view, name="index"),
    path('<int:pk>', views.DetailView.as_view(), name="detail"),
    path('book/add', views.AddBook.as_view(), name="add-book"),
    path('book/edit/<int:pk>', views.EditBook.as_view(), name="edit-book"),
    path('book/delete/<int:pk>', views.DeleteBook.as_view(), name="delete-book"),
    path('author/add', views.AddAuthor.as_view(), name="add-author"),
]

iLearn/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('', include('users.urls')),
]

# If in DEBUG mode, store all the files in a "media/" folder
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path('users/', views.UserFormView.as_view(), name="add-user"),
    path('logout/', views.logout_user, name="logout-user"),

    # Using built-in authentication system
    path('login/', auth_views.login, {'template_name': 'users/login.html'}, name="login")
]

books/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Author(models.Model):
    name=models.CharField(max_length=255)
    surname=models.CharField(max_length=255)
    
    class Meta:
        unique_together=['name', 'surname']

    def get_absolute_url(self):
        return reverse('books:index')

    def __str__(self):
        return f"{self.name} {self.surname}"

class Book(models.Model):
    author=models.ForeignKey(Author, on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE, default='')
    title=models.CharField(max_length=255, unique=True)
    isbn=models.CharField(max_length=13, unique=True)
    cover_image=models.FileField()

    def get_absolute_url(self):
        return reverse('books:detail', kwargs = {'pk':self.id})

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [ 'username', 'email', 'password' ]

books/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Count
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Author, Book
 
'''

Basic Views

'''
def index_view(request):
    try:
        return render(request, 'books/index.html', { 
            'books': Book.objects.all(),
            'user': request.user
        })
    except:
        return render(request, 'books/index.html', {
            'books': Book.objects.all(),
        })

class DetailView(generic.DetailView):
    model = Book
    template_name="books/detail.html"


'''

Crud Operations.

'''
class AddBook(LoginRequiredMixin, CreateView):
    model = Book
    fields = ['author' , 'title', 'isbn', 'cover_image']
    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AddBook, self).form_valid(form)

class EditBook(LoginRequiredMixin, UpdateView):
    model = Book
    fields = ['author' , 'title', 'isbn', 'cover_image']
    login_url = '/login/'
    template_name='books/edit_form.html'
    redirect_field_name = 'redirect_to'

class DeleteBook(LoginRequiredMixin, DeleteView):
    model = Book
    fields = ['author' , 'title', 'isbn']
    success_url = reverse_lazy('books:index')
    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    ''' 
    
        This function is used to convert get requests to post requests and let me omit
        a delete confirmation page. 

    '''
    def get(self, request, *args, **kwargs):
        book_publisher = Book.objects.filter(pk=self.kwargs['pk'])[0].user
        # If the publisher is not the authenticated user, don't delete the book!
        if(request.user != book_publisher):
            return render(request, 'books/index.html', {
                'books': Book.objects.all(),
                'b': book_publisher
            })    
        return self.post(request, *args, **kwargs)

class AddAuthor(LoginRequiredMixin, CreateView):
    model = Author
    fields = ['name' , 'surname']
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    template_name = "books/author_form.html"

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout
from django.views.generic import View
from .forms import UserForm

class UserFormView(View):
    form_class = UserForm
    template_name='users/registration-form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, { 'form': form })

    def post(self, request):
        form = self.form_class(request.POST)

        # If the form is valid, process the data... otherwise return an empty form.
        if form.is_valid():
            # Store the user informations but don't save it in the database yet.
            user = form.save(commit=False)

            # Clean up the data and store them in the database.
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)

            user.save()

            # Authenticate user.
            user = authenticate(username=username, password=password)

            if user is not None and user.is_active:
                login(request, user)
                return redirect('books:index')


        return render(request, self.template_name, { 'form': form })


def logout_user(request):
    logout(request)
    return redirect('books:index')

books/templates/books/author_form.html
{%extends 'base.html'%}
{%block include_css%}
    {%load staticfiles%}
    <link rel="stylesheet" href="{% static 'books/forms/style.css' %}">
    <link rel="stylesheet" href="{% static 'books/style.css' %}">
{%endblock%}
{%block title%}iLearn &raquo; Suggest an author!{%endblock%}

{%block body%}
    <h1 class="form-heading">Share your creations!</h1>
    <form action="" method="POST" enctype="multipart/form-data" class="iLearn-create">
        {%csrf_token%}
        {%include 'form-template.html'%}
        <div>
            <br><br><button type="submit" class="submit-btn">Submit</button>
        </div>
    </form>
{%endblock%}

books/templates/books/book_form.html
{%extends 'base.html'%}
{%block include_css%}
    {%load staticfiles%}
    <link rel="stylesheet" href="{% static 'books/forms/style.css' %}">
    <link rel="stylesheet" href="{% static 'books/style.css' %}">
{%endblock%}
{%block title%}iLearn &raquo; Share your creations!{%endblock%}

{%block body%}
    <h1 class="form-heading">Share your creations!</h1>
    <form action="" method="POST" enctype="multipart/form-data" class="iLearn-create">
        {%csrf_token%}
        {%include 'form-template.html'%}
        <div>
            <br><br><button type="submit" class="submit-btn">Submit</button>
        </div>
    </form>
{%endblock%}

books/templates/books/detail.html
{%extends 'base.html'%}

{%block include_css%}
    {%load staticfiles%}
    <link rel="stylesheet" href="{% static 'books/view_detail/style.css' %}">
    <link rel="stylesheet" href="{% static 'books/style.css' %}">
{%endblock%}

{%block body%}
    <div class="wrapper">
        {%if book%}
            <section class="iLearn-detail iLearn-book">
                <h1>{{book.title}}</h1>
                <div class="iLearn-book-cover" style="background-image: url({{book.cover_image.url}})"></div>
                <div class="iLearn-book-isbn"><span>ISBN: <b>{{book.isbn}}</b></span></div>
            </section>
        {%endif%}
    </div>
{%endblock%}

books/templates/books/edit_form.html
{%extends 'base.html'%}
{%block include_css%}
    {%load staticfiles%}
    <link rel="stylesheet" href="{% static 'books/forms/style.css' %}">
    <link rel="stylesheet" href="{% static 'books/style.css' %}">
{%endblock%}
{%block title%}iLearn &raquo; Share your creations!{%endblock%}

{%block body%}
    <h1 class="form-heading">Share your creations!</h1>
    {%if book.user == user%}
        <form action="" method="POST" enctype="multipart/form-data" class="iLearn-create">
            {%csrf_token%}
            {%include 'form-template.html'%}
            <div>
                <br><br><button type="submit" class="submit-btn">Submit</button>
            </div>
        </form>
    {%else%}
        <h1>Mhhh... you cannot edit this book!</h1>
    {%endif%}
{%endblock%}

books/templates/books/index.html
{%extends 'base.html'%}

{%block include_css%}
    {%load staticfiles%}
    <link rel="stylesheet" href="{% static 'books/view_index/style.css' %}">
{%endblock%}

{%block body%}
    {%if books%}
        <section class="iLearn-books">
            <h1>Latest Books</h1>
            {%for book in books%}
                <a href="{% url 'books:detail' book.id %}">
                    <section class="iLearn-book">
                            <div class="iLearn-book-cover" style="background-image: url({{book.cover_image.url}})"></div>
                            <div class="iLearn-book-author"><span>{{book.author}}</span></div>
                            {%if user.is_authenticated %}
                                <div class="iLearn-book-isbn"><span>{{book.isbn}}</span></div>
                                <div class="iLearn-book-operations">
                                    {%if book.user == user%}
                                        <a href="{%url 'books:edit-book' book.id%}">Edit</a>
                                        <a href="{%url 'books:delete-book' book.id%}">Delete</a>
                                    {%endif%}
                                </div>
                            {%endif%}
                    </section>
                </a>
            {%endfor%}
        </section>
    {%endif%}
{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en-EN">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="iLearn is an application built on top of the Django framework focused on sharing and create learning content">
    <meta name="keywords" content="learning django github piedimonte learn videos books free education free-education">
    <meta rel="author" content="http://github.com/mynameismaz">
    <link rel="canonical" href="">
    {%load staticfiles%}
    <link rel="stylesheet" href="{% static 'books/style.css' %}">
    {%block include_css%}{%endblock%}
    <title>{%block title%}iLearn{%endblock%}</title>
</head>
<body>
    <header class="iLearn-navbar">
        <nav>
            <ul>
                <li><a href="{%url 'books:index'%}">iLearn</a></li>
                {%if not user.is_authenticated %}
                    <li><a href="{%url 'users:login'%}">Login</a></li>
                    <li><a href="{%url 'users:add-user'%}">Sign In</a></li>
                {%else%}
                    <li><a href="{%url 'books:add-book'%}">Add Book</a></li>
                    <li><a href="{%url 'books:add-author'%}">Add Author</a></li>
                    <li class="logged-as">Logged as <b>{{user}}</b></li>
                    <li><a href="{%url 'users:logout-user'%}">Logout</a></li>
                {%endif%}
            </ul>
        </nav>
    </header>

    <section class="iLearn">
        {%block body%}
        {%endblock%}
    </section>
</body>
</html>

templates/form-template.html
{% for field in form %}
    <div class="error">
        <p>{{ field.errors }}</p>
    </div>
    <div>
        <label>{{ field.label_tag }}</label>
        {{ field }}
    </div>
{% endfor %}

users/templates/users/login.html
{%extends 'base.html'%}
{%block include_css%}
    {%load staticfiles%}
    <link rel="stylesheet" href="{% static 'books/forms/style.css' %}">
    <link rel="stylesheet" href="{% static 'books/style.css' %}">
{%endblock%}
{%block title%}iLearn &raquo; Login!{%endblock%}

{%block body%}
  <h1 class="form-heading">Login up!</h1>
  <form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit" class="submit-btn">Submit</button>
  </form>
{%endblock%}

users/templates/users/registration-form.html
{%extends 'base.html'%}
{%block include_css%}
    {%load staticfiles%}
    <link rel="stylesheet" href="{% static 'books/forms/style.css' %}">
    <link rel="stylesheet" href="{% static 'books/style.css' %}">
{%endblock%}
{%block title%}iLearn &raquo; Sign up today!{%endblock%}

{%block body%}
    <h1 class="form-heading">Sign up!</h1>
    <form action="" method="POST" enctype="multipart/form-data" class="iLearn-create">
        {%csrf_token%}
        {%include 'form-template.html'%}
        <div>
            <br><br><button type="submit" class="submit-btn">Submit</button>
        </div>
    </form>
{%endblock%}